name: Deploy site to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simple test
        run: |
          test -f site/index.html
          echo "site/index.html found ✅"

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload site to EC2 staging folder
        run: |
          ssh "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "mkdir -p /opt/cloudsupportlab/site"
          scp -r site/* "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/opt/cloudsupportlab/site/"

      - name: Deploy to web root + reload nginx
        run: |
          ssh "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" "
            sudo rsync -a --delete /opt/cloudsupportlab/site/ /var/www/html/ &&
            sudo nginx -t &&
            sudo systemctl reload nginx
          "
